services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_DOCKER}"
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql